databases:
  - name: postgres
    ipAllowList: []
    databaseName: ticketly_prod_887
    user: ticketly_prod_887_user

services:
  - type: web
    name: ticketly
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false